### ISSUE TITLE
Fix of Articles Section - Ekim

### ISSUE THREAD

**Issue by OrcunSelbasan** [ekimcem/Simple_Portfolio#4]
https://github.com/ekimcem/Simple_Portfolio/blob/44bf340faa7997eec161beec5dbf6bd8cfeb62d2/index.html#L112

## Articles Section

Tags are overflowing when I shrink the page. I think the problem might be about <a> tags as those are inline elements. I'd handle this tags part by using list items that are block-level elements:
```
<ul class=".....">
   <li class="...">Life Style</li>
   ...
</ul>
```

**Comment by ekimcem** [comment]
Solved the problem with bootstrap. Changed the flex type to the block except for large or x-large screens.
Also, I have tried to HTML unordered list. It is worked too. Thank you for your suggestion.

It changed to : 
` <div class="container d-lg-flex d-block justify-content-between ps-4 pe-4 text-center">`
