### ISSUE TITLE
Fixes of Footer Section - Ekim

### ISSUE THREAD

**Issue by OrcunSelbasan** [ekimcem/Simple_Portfolio#5]
https://github.com/ekimcem/Simple_Portfolio/blob/22b0f12c2913587d76d31aa08d340ac60794a2ae/index.html#L150

## Footer Section

It will have small fixes :
- Reducing the gap between "Stay connected" and mail
- Add top and bottom margin to logos
- Fix the gap between logos

Good luck and have fun!

**Comment by ekimcem** [comment]
- The gap between "Stay Connected and Mail reduced.
- Logos are relocated.
- The logo section takes 25% of screen width now ( with a max-width of 350px and a min-width of 250px).

Thank you for your support.
